# Generated by Django 5.0.2 on 2024-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0010_kafeel_monthly_amount_student_monthly_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='month',
            field=models.IntegerField(choices=[(4, 'Muharram'), (5, 'Safar'), (6, "Rabi' al-Awwal"), (7, "Rabi' al-Thani"), (8, 'Jumada al-Awwal'), (9, 'Jumada al-Thani'), (10, 'Rajab'), (11, "Sha'ban"), (12, 'Ramadan'), (1, 'Shawwal'), (2, "Dhu al-Qi'dah"), (3, 'Dhu al-Hijjah')], default=1),
            preserve_default=False,
        ),
    ]
