# Generated by Django 5.0.2 on 2024-03-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0011_progress_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='month',
            field=models.CharField(choices=[(1, 'Muharram'), (2, 'Safar'), (3, "Rabi' al-Awwal"), (4, "Rabi' al-Thani"), (5, 'Jumada al-Awwal'), (6, 'Jumada al-Thani'), (7, 'Rajab'), (8, "Sha'ban"), (9, 'Ramadan'), (10, 'Shawwal'), (11, "Dhu al-Qi'dah"), (12, 'Dhu al-Hijjah')], max_length=255),
        ),
    ]
