# Generated by Django 5.0.2 on 2024-03-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0012_alter_progress_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='month',
        ),
    ]
