# Generated by Django 5.0.2 on 2024-03-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0013_remove_progress_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='month',
            field=models.CharField(choices=[('Muharram', 'Muharram'), ('Safar', 'Safar'), ('Rabi al-Awwal', 'Rabi al-Awwal'), ('Rabi al-Thani', 'Rabi al-Thani'), ('Jumada al-Awwal', 'Jumada al-Awwal'), ('Jumada al-Thani', 'Jumada al-Thani'), ('Rajab', 'Rajab'), ('Sha`ban', 'Sha`ban'), ('Ramadan', 'Ramadan'), ('Shawwal', 'Shawwal'), ('Dhu al-Qi`dah', 'Dhu al-Qi`dah'), ('Dhu al-Hijjah', 'Dhu al-Hijjah')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
