# Generated by Django 5.0.2 on 2024-03-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0014_progress_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
