# Generated by Django 5.0.2 on 2024-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0015_alter_progress_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='month',
            field=models.CharField(choices=[('Muharram', 'Muharram'), ('Safar', 'Safar'), ('Rabi al-Awwal', 'Rabi al-Awwal')], max_length=20),
        ),
    ]
