# Generated by Django 5.0.2 on 2024-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0017_progress_payment_status_alter_progress_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='study_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
