# Generated by Django 5.0.2 on 2024-03-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0018_alter_progress_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='receipt_number',
            field=models.CharField(max_length=255, null=True, unique=False),
        ),
    ]
