# Generated by Django 5.0.2 on 2024-03-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0019_alter_progress_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='receipt_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
