# Generated by Django 5.0.2 on 2024-03-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0020_alter_progress_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='receipt_number',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True, unique=True),
        ),
    ]
