# Generated by Django 5.0.2 on 2024-03-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0022_alter_progress_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('study_report', models.TextField()),
                ('paid_date', models.DateTimeField()),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10)),
                ('mahina', models.CharField(max_length=50)),
                ('kafeel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifalat.kafeel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifalat.student')),
            ],
        ),
    ]
