# Generated by Django 5.0.2 on 2024-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0023_record'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('student', 'month')},
        ),
        migrations.AlterField(
            model_name='record',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='study_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='record',
            name='kafeel',
        ),
        migrations.RemoveField(
            model_name='record',
            name='mahina',
        ),
    ]
