# Generated by Django 5.0.2 on 2024-03-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0024_alter_record_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='mahina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='receipt_number',
            field=models.CharField(blank=True, default='--', max_length=255),
        ),
    ]
