# Generated by Django 5.0.2 on 2024-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0025_record_mahina_alter_record_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10),
        ),
    ]
