# Generated by Django 5.0.2 on 2024-03-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0028_alter_record_amount_paid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='record',
            name='mahina',
            field=models.CharField(blank=True, choices=[('Muharram', 'Muharram'), ('Safar', 'Safar'), ("Rabi' al-awwal", "Rabi' al-awwal"), ("Rabi' al-thani", "Rabi' al-thani"), ('Jumada al-awwal', 'Jumada al-awwal'), ('Jumada al-thani', 'Jumada al-thani'), ('Rajab', 'Rajab'), ("Sha'ban", "Sha'ban"), ('Ramadan', 'Ramadan'), ('Shawwal', 'Shawwal'), ("Dhu al-Qi'dah", "Dhu al-Qi'dah"), ('Dhu al-Hijjah', 'Dhu al-Hijjah')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='month',
            field=models.CharField(choices=[('Muharram', 'Muharram'), ('Safar', 'Safar'), ("Rabi' al-awwal", "Rabi' al-awwal"), ("Rabi' al-thani", "Rabi' al-thani"), ('Jumada al-awwal', 'Jumada al-awwal'), ('Jumada al-thani', 'Jumada al-thani'), ('Rajab', 'Rajab'), ("Sha'ban", "Sha'ban"), ('Ramadan', 'Ramadan'), ('Shawwal', 'Shawwal'), ("Dhu al-Qi'dah", "Dhu al-Qi'dah"), ('Dhu al-Hijjah', 'Dhu al-Hijjah')], max_length=20),
        ),
    ]
