# Generated by Django 5.0.2 on 2024-03-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0029_alter_record_unique_together_alter_record_mahina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='mahina',
        ),
    ]
