# Generated by Django 5.0.2 on 2024-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0030_remove_record_mahina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='study_report',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
