# Generated by Django 5.1.3 on 2025-06-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0031_alter_record_study_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='parent_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='kifalat.record'),
        ),
    ]
