# Generated by Django 5.1.3 on 2025-06-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0032_record_parent_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='parent_payment',
        ),
    ]
